config/routes.rb
RailsRoot::Application.routes.draw do
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  attr_accessible :accessories, :age, :clothes, :emotion, :eye_color, :face_bottom, :face_left, :face_right, :face_top, :full_bottom, :full_left, :full_right, :full_top, :gender, :hair_color, :hair_length, :hair_style, :height, :img_height, :img_width, :makeup, :physique, :race, :skin_color, :tags, :url, :weight
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pics }
    end
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
    @pic = Pic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pic }
    end
  end

  # GET /pics/new
  # GET /pics/new.json
  def new
    @pic = Pic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pic }
    end
  end

  # GET /pics/1/edit
  def edit
    @pic = Pic.find(params[:id])
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(params[:pic])

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render json: @pic, status: :created, location: @pic }
      else
        format.html { render action: "new" }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pics/1
  # PUT /pics/1.json
  def update
    @pic = Pic.find(params[:id])

    respond_to do |format|
      if @pic.update_attributes(params[:pic])
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to pics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% content_for(:head) do %>
  <%= stylesheet_link_tag "jcrop/jquery.Jcrop" %>
  <%= javascript_include_tag "jcrop/jquery.Jcrop" %>
  <%= javascript_include_tag "pics/_form" %>
  <% end %>

  <div class="picFormLeftColumn ">
    <p>
      <div class="picFormImgBox" id="display">
        <% if @pic.url == nil || @pic.url == "" %>
          <%= image_tag "/assets/rails.png", :id => "picDisplay" %>
        <% else %>
          <%= image_tag @pic.url, :id => "picDisplay" %>
        <% end %>
      </div>
    </p>
    <div class="spacer"><p><hr></p></div>
    <p>
      <div class="picFormImgBox" id="faceDisplay">
        <% if @pic.url == nil || @pic.url == "" %>
          <%= image_tag "/assets/rails.png", :id => "facePic" %>
        <% else %>
          <%= image_tag @pic.url, :id => "facePic" %>
        <% end %>
      </div>
      <div class="leftTabWrapper">
        Crop this image<br>to a headshot.
      </div>
    </p>
    <div class="spacer"><p><hr></p></div>
    <p>
      <div class="picFormImgBox" id="fullDisplay">
        <% if @pic.url == nil || @pic.url == "" %>
          <%= image_tag "/assets/rails.png", :id => "fullPic" %>
        <% else %>
          <%= image_tag @pic.url, :id => "fullPic" %>
        <% end %>
      </div>
      <div class="leftTabWrapper">
          Crop this image<br>to a full body shot.
      </div>
    </p>
  </div>

  <div class="picFormRightColumn">
    <div class="field">
      <%= f.label :url %><br />
      <%= f.text_field :url %>
    </div>
    <div class="field">
      <%= f.hidden_field :img_height %>
    </div>
    <div class="field">
      <%= f.hidden_field :img_width %>
    </div>
    <div class="field">
      <%= f.hidden_field :full_top %>
    </div>
    <div class="field">
      <%= f.hidden_field :full_bottom %>
    </div>
    <div class="field">
      <%= f.hidden_field :full_left %>
    </div>
    <div class="field">
      <%= f.hidden_field :full_right %>
    </div>
    <div class="field">
      <%= f.hidden_field :face_top %>
    </div>
    <div class="field">
      <%= f.hidden_field :face_bottom %>
    </div>
    <div class="field">
      <%= f.hidden_field :face_left %>
    </div>
    <div class="field">
      <%= f.hidden_field :face_right %>
    </div>
    <div class="field">
      <%= f.label :gender %><br />
      <%= f.text_field :gender %>
    </div>
    <div class="field">
      <%= f.label :age %><br />
      <%= f.number_field :age %>
    </div>
    <div class="field">
      <%= f.label :height %><br />
      <%= f.number_field :height %>
    </div>
    <div class="field">
      <%= f.label :weight %><br />
      <%= f.text_field :weight %>
    </div>
    <div class="field">
      <%= f.label :physique %><br />
      <%= f.text_field :physique %>
    </div>
    <div class="field">
      <%= f.label :skin_color %><br />
      <%= f.text_field :skin_color %>
    </div>
    <div class="field">
      <%= f.label :race %><br />
      <%= f.text_field :race %>
    </div>
    <div class="field">
      <%= f.label :hair_color %><br />
      <%= f.text_field :hair_color %>
    </div>
    <div class="field">
      <%= f.label :hair_length %><br />
      <%= f.text_field :hair_length %>
    </div>
    <div class="field">
      <%= f.label :hair_style %><br />
      <%= f.text_field :hair_style %>
    </div>
    <div class="field">
      <%= f.label :eye_color %><br />
      <%= f.text_field :eye_color %>
    </div>
    <div class="field">
      <%= f.label :clothes %><br />
      <%= f.text_field :clothes %>
    </div>
    <div class="field">
      <%= f.label :makeup %><br />
      <%= f.text_field :makeup %>
    </div>
    <div class="field">
      <%= f.label :accessories %><br />
      <%= f.text_field :accessories %>
    </div>
    <div class="field">
      <%= f.label :emotion %><br />
      <%= f.text_field :emotion %>
    </div>
    <div class="field">
      <%= f.label :tags %><br />
      <%= f.text_field :tags %>
    </div>
  </div>
  <div class="spacer">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %><br />

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<h1>Listing pics</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Full top</th>
    <th>Full bottom</th>
    <th>Full left</th>
    <th>Full right</th>
    <th>Face top</th>
    <th>Face bottom</th>
    <th>Face left</th>
    <th>Face right</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Weight</th>
    <th>Physique</th>
    <th>Skin color</th>
    <th>Race</th>
    <th>Hair color</th>
    <th>Hair length</th>
    <th>Hair style</th>
    <th>Eye color</th>
    <th>Clothes</th>
    <th>Makeup</th>
    <th>Accessories</th>
    <th>Emotion</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pics.each do |pic| %>
  <tr>
    <td><%= pic.url %></td>
    <td><%= pic.full_top %></td>
    <td><%= pic.full_bottom %></td>
    <td><%= pic.full_left %></td>
    <td><%= pic.full_right %></td>
    <td><%= pic.face_top %></td>
    <td><%= pic.face_bottom %></td>
    <td><%= pic.face_left %></td>
    <td><%= pic.face_right %></td>
    <td><%= pic.gender %></td>
    <td><%= pic.age %></td>
    <td><%= pic.weight %></td>
    <td><%= pic.physique %></td>
    <td><%= pic.skin_color %></td>
    <td><%= pic.race %></td>
    <td><%= pic.hair_color %></td>
    <td><%= pic.hair_length %></td>
    <td><%= pic.hair_style %></td>
    <td><%= pic.eye_color %></td>
    <td><%= pic.clothes %></td>
    <td><%= pic.makeup %></td>
    <td><%= pic.accessories %></td>
    <td><%= pic.emotion %></td>
    <td><%= pic.tags %></td>
    <td><%= link_to 'Show', pic %></td>
    <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
    <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= link_to 'Back', pics_path %>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <b>Image:</b>
  <%= showPic(:pic => @pic) %>
</p>

<p>
  <b>Face:</b>
  <%= showPic(:pic => @pic, :crop => "face") %>
</p>

<p>
  <b>Full Body:</b>
  <%= showPic(:pic => @pic, :crop => "full") %>
</p>

<p>
  <b>Gender:</b>
  <%= @pic.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @pic.age %>
</p>

<p>
  <b>Weight:</b>
  <%= @pic.weight %>
</p>

<p>
  <b>Physique:</b>
  <%= @pic.physique %>
</p>

<p>
  <b>Skin color:</b>
  <%= @pic.skin_color %>
</p>

<p>
  <b>Race:</b>
  <%= @pic.race %>
</p>

<p>
  <b>Hair color:</b>
  <%= @pic.hair_color %>
</p>

<p>
  <b>Hair length:</b>
  <%= @pic.hair_length %>
</p>

<p>
  <b>Hair style:</b>
  <%= @pic.hair_style %>
</p>

<p>
  <b>Eye color:</b>
  <%= @pic.eye_color %>
</p>

<p>
  <b>Clothes:</b>
  <%= @pic.clothes %>
</p>

<p>
  <b>Makeup:</b>
  <%= @pic.makeup %>
</p>

<p>
  <b>Accessories:</b>
  <%= @pic.accessories %>
</p>

<p>
  <b>Emotion:</b>
  <%= @pic.emotion %>
</p>

<p>
  <b>Tags:</b>
  <%= @pic.tags %>
</p>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>